version: "3.8"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  solr:
    image: solr
    ports:
      - "8983:8983"
  tomcat:
    build: .
    ports:
      - "8888:8080"
